create table apps.dept (
    deptno number(2, 0),
    dname  varchar2(14 byte),
    loc    varchar2(13 byte)
);

alter table apps.dept add primary key ( deptno )
    using index enable;


-- sqlcl_snapshot {"hash":"0e50427c03fad0e71c43daf64ea894f881629c26","type":"TABLE","name":"DEPT","schemaName":"APPS","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>APPS</SCHEMA><NAME>DEPT</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>DEPTNO</NAME><DATATYPE>NUMBER</DATATYPE><PRECISION>2</PRECISION><SCALE>0</SCALE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>DNAME</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>14</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>LOC</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>13</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM></COL_LIST><PRIMARY_KEY_CONSTRAINT_LIST><PRIMARY_KEY_CONSTRAINT_LIST_ITEM><COL_LIST><COL_LIST_ITEM><NAME>DEPTNO</NAME></COL_LIST_ITEM></COL_LIST><USING_INDEX></USING_INDEX></PRIMARY_KEY_CONSTRAINT_LIST_ITEM></PRIMARY_KEY_CONSTRAINT_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}